- shell: rpm -i http://fedora-epel.mirror.lstn.net/7/x86_64/e/epel-release-7-5.noarch.rpm
  args:
      creates: /etc/yum.repos.d/epel.repo

- yum: name={{ item }} 
       state=latest
  with_items:
    - gdal
    - rsync     
- unarchive:
    src=deployer-0.1-SNAPSHOT.tgz
    dest=/opt/
- file: 
    path=/opt/deployer
    state=link
    src=/opt/deployer-0.1-SNAPSHOT
- copy: 
    src=geoserver-files
    dest=/opt/deployer-0.1-SNAPSHOT/
    mode=0600
- cron: 
    minute=5
    name="Cull geoserver deployments"
    job="/opt/deployer/bin/deployer -main com.radiantblue.deployer.Cull"
