- unarchive: 
    src=kafka_2.10-0.8.2.1.tgz
    dest=/opt/
- file:
    path=/opt/kafka
    state=link 
    src=/opt/kafka_2.10-0.8.2.1 
- copy: 
    src=etc/
    dest=/etc/
    owner=root
- lineinfile:
    dest=/opt/kafka/config/server.properties
    state=present
    line="advertised.host.name={{ansible_eth1.ipv4.address}}"
- service:
    name=kafka
    enabled=yes
    state=started

