---
- postgresql_user: name=piazza password=secret
- postgresql_db: name=metadata
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 owner=piazza
- postgresql_privs: >
        database=metadata
        state=present
        privs=ALL
        type=database
        roles=piazza
        grant_option=yes
- postgresql_ext: name=postgis db=metadata
- copy: src=metadata_tables.sql dest=/tmp/
- command: psql metadata -f /tmp/metadata_tables.sql
- postgresql_privs: >
        database=metadata
        state=present
        privs=ALL
        type=table
        objs=ALL_IN_SCHEMA
        roles=piazza
        grant_option=yes
- postgresql_privs: >
        database=metadata
        state=present
        privs=ALL
        type=sequence
        objs=ALL_IN_SCHEMA
        roles=piazza
        grant_option=yes

- postgresql_db: name=geodata
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 owner=piazza
- postgresql_privs: >
        database=geodata
        state=present
        privs=ALL
        type=database
        roles=piazza
        grant_option=yes
- postgresql_ext: name=postgis db=geodata
- copy: src=geodata_setup.sql dest=/tmp/
- command: psql geodata -f /tmp/geodata_tables.sql
- postgresql_privs: >
        database=geodata
        state=present
        privs=ALL
        type=table
        objs=ALL_IN_SCHEMA
        roles=piazza
        grant_option=yes
- postgresql_privs: >
        database=geodata
        state=present
        privs=ALL
        type=sequence
        objs=ALL_IN_SCHEMA
        roles=piazza
        grant_option=yes
