---
- postgresql_user: name=geoint password=secret
- postgresql_db: name=metadata
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 owner=geoint
- postgresql_privs: >
        database=metadata
        state=present
        privs=ALL
        type=database
        roles=geoint
        grant_option=yes
- postgresql_ext: name=postgis db=metadata
- copy: src=metadata_tables.sql dest=/tmp/
- command: psql metadata -f /tmp/metadata_tables.sql
- postgresql_privs: >
        database=metadata
        state=present
        privs=ALL
        type=table
        objs=ALL_IN_SCHEMA
        roles=geoint
        grant_option=yes
- postgresql_privs: >
        database=metadata
        state=present
        privs=ALL
        type=sequence
        objs=ALL_IN_SCHEMA
        roles=geoint
        grant_option=yes
