---
- hosts: database
  sudo: yes
  roles:
      - postgis
- hosts: messaging
  sudo: yes
  roles:
      - kafka
      - storm
      - uploader
      - normalizer
      - deployer
  tasks:
      - script: deploy_kafka_queues.sh creates=/opt/kafka/deployed_geoint_queues
      - script: deploy_storm_topologies.sh creates=/opt/storm/deployed_geoint_topologies
- hosts: geoserver
  sudo: yes
  roles:
      - { role: geoserver, control_port: 8181, http_port: 8081, name: geoserver1 }
      - { role: geoserver, control_port: 8182, http_port: 8082, name: geoserver2 }
      - ogcproxy
