---
- hosts: all
  sudo: yes
  tasks:
    - yum: name=libselinux-python state=latest
    - lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"
- hosts: database
  sudo: yes
  roles:
      - postgis
- hosts: messaging
  sudo: yes
  roles:
      - kafka
      - uploader
      - normalizer
      - deployer
  tasks:
      - script: deploy_kafka_queues.sh creates=/opt/kafka/deployed_piazza_queues
- hosts: geoserver
  sudo: yes
  roles:
      - { role: geoserver, control_port: 8181, http_port: 8081, name: geoserver1, jmx_port: 8281 }
      - { role: geoserver, control_port: 8182, http_port: 8082, name: geoserver2, jmx_port: 8282 }
      - ogcproxy
